### ISSUE TITLE
PDEX Client Test is confusing

### ISSUE THREAD

**Issue by ktilcu** [inferno-framework/davinci-pdex-test-kit#18]
Based on the postman [collection](https://github.com/inferno-framework/davinci-pdex-test-kit/blob/main/PDEX.postman_collection.json), it seems like the following happens:

1. Payer 1 has a patient with an internal ID of `999` 
2. Payer 2 has a patient with a member ID in a target system of `55678`
3. Payer 1 submits a $member-match request to Payer 2 indicating that the member ID in Payer 2 system might be `55678`
4. Payer 2 responds with a unique identifier of `99999`

This is where things get a bit confusing. The resource requests in the postman collection seem to use a few different IDs. For requests to Payer 2 I see:
- `/Patient?identifier=99999`
- `/Encounter?patient=999`
- `/Patient?_id=999`
- `/Patient/999/$everything`

I'm surprised Payer 1 would query any resources on Payer 2 using their own internal ID instead of the Payer 2 identifier.

I recognize this is meant to test something slightly separate but wanted to see if I am misunderstanding this or if I could clean up the Postman collection a bit?

**Comment by Shaumik-Ashraf** [comment]
Your understanding is mostly correct. Payer 1 submits a $member-match request with Member ID `55678` to Payer 2, and Payer 2 returns a "matched" patient with a different Member ID `99999`. There is no guarantee for Identifier values for patients in different healthcare systems to be the same, and what constitutes a "match" in Payer 2's system is upto Payer 2 (i.e: it may be based on demographics or contextual data).

Additionally Payer 1 must send its patient's resource id of `999` so other resources in that request can make local references to it (`"reference": "Patient/999"`) which the [$member-match operation explicitly mandates](https://hl7.org/fhir/us/davinci-hrex/STU1/OperationDefinition-member-match.html#resolving-parameter-references). This does not necessarily have to be the internal id (i.e: an SQL primary index) of the resource for Payer 1. The next query is Payer 1 using Payer 2's identifier value to get Payer 2's patient resource id, which in our case happens to be the same id of `999`, but whatever resource id is returned by Payer 2 should be used as patient id for all following FHIR queries. Querying other resources by identifier is not in the Payer-to-Payer workflow specification.

Also thank you for pointing this out, the two distinct resource ids having the same value causes some confusion, so we'll clean this up in PR #16.

**Comment by ktilcu** [comment]
Ok! Awesome. Thanks for the clarity and the changes!
